// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrJWNUNMpilaigYCxrfKSAn6nrXMyDQ9g',
    appId: '1:1048175666591:web:591f62cda910deefcdc9aa',
    messagingSenderId: '1048175666591',
    projectId: 'garnetbool',
    authDomain: 'garnetbool.firebaseapp.com',
    storageBucket: 'garnetbool.appspot.com',
    measurementId: 'G-R0EPF584X0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKGPB7FokbOWPyu3qqVimtNZ3W3Ay4ZTk',
    appId: '1:1048175666591:android:785ea5f53878b10acdc9aa',
    messagingSenderId: '1048175666591',
    projectId: 'garnetbool',
    storageBucket: 'garnetbool.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh7cIOeuNh9mlqJpvWz8ygNhWutnFjdQY',
    appId: '1:1048175666591:ios:5c4376e5cf5a71b1cdc9aa',
    messagingSenderId: '1048175666591',
    projectId: 'garnetbool',
    storageBucket: 'garnetbool.appspot.com',
    androidClientId: '1048175666591-i9t938u5t4pa0a2ts857enj98hneakdl.apps.googleusercontent.com',
    iosClientId: '1048175666591-9o5huio2b3lpq1skdpq31tol57scgfp4.apps.googleusercontent.com',
    iosBundleId: 'garnetbook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh7cIOeuNh9mlqJpvWz8ygNhWutnFjdQY',
    appId: '1:1048175666591:ios:c48886ce427d05e8cdc9aa',
    messagingSenderId: '1048175666591',
    projectId: 'garnetbool',
    storageBucket: 'garnetbool.appspot.com',
    androidClientId: '1048175666591-i9t938u5t4pa0a2ts857enj98hneakdl.apps.googleusercontent.com',
    iosClientId: '1048175666591-2pnacv22kp5ngq2pu883f3at2a2pq2gj.apps.googleusercontent.com',
    iosBundleId: 'com.example.longLife',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrJWNUNMpilaigYCxrfKSAn6nrXMyDQ9g',
    appId: '1:1048175666591:web:702538f70d362793cdc9aa',
    messagingSenderId: '1048175666591',
    projectId: 'garnetbool',
    authDomain: 'garnetbool.firebaseapp.com',
    storageBucket: 'garnetbool.appspot.com',
    measurementId: 'G-91FKQ6STDG',
  );

}